export const navigation = [
  {
    title: "Dashboard",
    path: "/",
    icon: "mdi-grid-large",
    type: "dashboard",
    children: [],
    roles: ["member", "super-administrator"],
  },
  {
    title: "Members Area",
    path: "",
    icon: "",
    type: "category",
    children: [
      {
        title: "Loans",
        path: "/loans",
        icon: "mdi-bank",
        type: "link",
        children: [],
        roles: ["member", "super-administrator"],
      },
      {
        title: "Requests",
        path: "/service/requests",
        icon: "mdi-chart-arc",
        type: "link",
        children: [],
        roles: ["member", "super-administrator"],
      },
      {
        title: "Guarantee Loans",
        path: "/grant-loans",
        icon: "mdi-check-all",
        type: "link",
        children: [],
        roles: ["member", "super-administrator"],
      },
    ],
    roles: ["member", "super-administrator"],
  },
  {
    title: "Secretariate",
    path: "",
    icon: "",
    type: "category",
    children: [
      {
        title: "Loan Decision",
        path: "/loan/decision",
        icon: "mdi-bowling",
        type: "link",
        children: [],
        roles: ["secretariate", "super-administrator"],
      },
      {
        title: "Approve Loans",
        path: "/approve/loans",
        icon: "mdi-animation",
        type: "link",
        children: [],
        roles: [
          "treasury-officer",
          "general-secretary",
          "president",
          "super-administrator",
        ],
      },
    ],
    roles: [
      "secretariate",
      "treasury-officer",
      "general-secretary",
      "president",
      "super-administrator",
    ],
  },
  {
    title: "Administration",
    path: "",
    icon: "",
    type: "category",
    children: [
      {
        title: "Roles",
        path: "/roles",
        icon: "mdi-floor-plan",
        type: "link",
        children: [],
        roles: ["super-administrator"],
      },
      {
        title: "Settings",
        path: "/settings",
        icon: "mdi-settings",
        type: "link",
        children: [],
        roles: ["super-administrator"],
      },
      {
        title: "Configuration",
        path: "/configuration",
        icon: "mdi-dns",
        type: "link",
        children: [],
        roles: ["super-administrator", "administrator", "general-secretary"],
      },
      {
        title: "Members",
        path: "/members",
        icon: "mdi-account-multiple",
        type: "link",
        children: [],
        roles: ["super-administrator", "administrator"],
      },
    ],
    roles: ["super-administrator", "administrator", "general-secretary"],
  },
  {
    title: "Finance Control",
    path: "",
    icon: "",
    type: "category",
    children: [
      {
        title: "Budget",
        path: "",
        icon: "mdi-credit-card-multiple",
        type: "dropdown",
        children: [
          {
            title: "Budget Heads",
            path: "/budget-heads",
            icon: "",
            type: "sub-link",
            children: [],
            roles: ["super-administrator", "account-officer"],
          },
          {
            title: "Sub Budget Heads",
            path: "/sub-budget-heads",
            icon: "",
            type: "sub-link",
            children: [],
            roles: ["super-administrator", "account-officer"],
          },
          {
            title: "Funds",
            path: "/funds",
            icon: "",
            type: "sub-link",
            children: [],
            roles: ["super-administrator", "account-officer", "secretary"],
          },
        ],
        roles: ["super-administrator", "account-officer", "secretary"],
      },
      {
        title: "Accounts",
        path: "",
        icon: "mdi-chart-line",
        type: "dropdown",
        children: [
          {
            title: "Account Codes",
            path: "/account-codes",
            icon: "",
            type: "sub-link",
            children: [],
            roles: ["super-administrator", "account-officer"],
          },
          {
            title: "Chart Of Accounts",
            path: "/chart-of-accounts",
            icon: "",
            type: "sub-link",
            children: [],
            roles: ["super-administrator", "account-officer"],
          },
          {
            title: "Expenditures",
            path: "/expenditures",
            icon: "",
            type: "sub-link",
            children: [],
            roles: ["super-administrator", "account-officer"],
          },
          {
            title: "Batch Payments",
            path: "/batch/payments",
            icon: "",
            type: "sub-link",
            children: [],
            roles: ["super-administrator", "account-officer"],
          },
          {
            title: "Payments",
            path: "/payments",
            icon: "",
            type: "sub-link",
            children: [],
            roles: ["super-administrator", "account-officer"],
          },
        ],
        roles: ["super-administrator", "account-officer"],
      },
    ],
    roles: ["super-administrator", "account-officer", "secretary"],
  },
  {
    title: "Resource Management",
    path: "",
    icon: "",
    type: "category",
    children: [
      {
        title: "Contributions",
        path: "",
        icon: "mdi-package-variant",
        type: "dropdown",
        children: [
          {
            title: "Deductions",
            path: "/contribution/deductions",
            icon: "",
            type: "sub-link",
            children: [],
            roles: ["super-administrator", "account-officer"],
          },
          {
            title: "Credit Accounts",
            path: "/credit/accounts",
            icon: "",
            type: "sub-link",
            children: [],
            roles: ["super-administrator", "secretary"],
          },
        ],
        roles: ["super-administrator", "account-officer", "secretary"],
      },
    ],
    roles: ["super-administrator", "account-officer", "secretary"],
  },
  {
    title: "Console",
    path: "",
    icon: "",
    type: "category",
    children: [
      {
        title: "Import",
        path: "/imports",
        icon: "mdi-file-import",
        type: "link",
        children: [],
        roles: ["super-administrator"],
      },
    ],
    roles: ["super-administrator"],
  },
];
